#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Player:
  X = 1
  O = 2

  _VALUES_TO_NAMES = {
    1: "X",
    2: "O",
  }

  _NAMES_TO_VALUES = {
    "X": 1,
    "O": 2,
  }


class Move:
  """
  Attributes:
   - player
   - position
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'player', None, None, ), # 1
    (2, TType.I32, 'position', None, None, ), # 2
  )

  def __init__(self, player=None, position=None,):
    self.player = player
    self.position = position

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.player = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.position = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Move')
    if self.player is not None:
      oprot.writeFieldBegin('player', TType.I32, 1)
      oprot.writeI32(self.player)
      oprot.writeFieldEnd()
    if self.position is not None:
      oprot.writeFieldBegin('position', TType.I32, 2)
      oprot.writeI32(self.position)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.player is None:
      raise TProtocol.TProtocolException(message='Required field player is unset!')
    if self.position is None:
      raise TProtocol.TProtocolException(message='Required field position is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Game:
  """
  Attributes:
   - id
   - players
   - moves
   - nextMove
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'id', None, None, ), # 1
    (2, TType.MAP, 'players', (TType.STRING,None,TType.I32,None), None, ), # 2
    (3, TType.LIST, 'moves', (TType.STRUCT,(Move, Move.thrift_spec)), None, ), # 3
    (4, TType.I32, 'nextMove', None, None, ), # 4
  )

  def __init__(self, id=None, players=None, moves=None, nextMove=None,):
    self.id = id
    self.players = players
    self.moves = moves
    self.nextMove = nextMove

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.id = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.MAP:
          self.players = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin() 
          for _i4 in xrange(_size0):
            _key5 = iprot.readString();
            _val6 = iprot.readI32();
            self.players[_key5] = _val6
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.LIST:
          self.moves = []
          (_etype10, _size7) = iprot.readListBegin()
          for _i11 in xrange(_size7):
            _elem12 = Move()
            _elem12.read(iprot)
            self.moves.append(_elem12)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.nextMove = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Game')
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.STRING, 1)
      oprot.writeString(self.id)
      oprot.writeFieldEnd()
    if self.players is not None:
      oprot.writeFieldBegin('players', TType.MAP, 2)
      oprot.writeMapBegin(TType.STRING, TType.I32, len(self.players))
      for kiter13,viter14 in self.players.items():
        oprot.writeString(kiter13)
        oprot.writeI32(viter14)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.moves is not None:
      oprot.writeFieldBegin('moves', TType.LIST, 3)
      oprot.writeListBegin(TType.STRUCT, len(self.moves))
      for iter15 in self.moves:
        iter15.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.nextMove is not None:
      oprot.writeFieldBegin('nextMove', TType.I32, 4)
      oprot.writeI32(self.nextMove)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    if self.id is None:
      raise TProtocol.TProtocolException(message='Required field id is unset!')
    if self.players is None:
      raise TProtocol.TProtocolException(message='Required field players is unset!')
    if self.moves is None:
      raise TProtocol.TProtocolException(message='Required field moves is unset!')
    if self.nextMove is None:
      raise TProtocol.TProtocolException(message='Required field nextMove is unset!')
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
